=== diogocapela/isep-lprog/PL04/ex04.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" attributeFormDefault="unqualified" 
    xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="ex04.xml">



    <xs:element name="toptracks">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="track" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="artist">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="mbid" type="xs:string" />
                                        <xs:element name="url" type="xs:string" />
                                    </xs:sequence>
                                    <xs:attribute name="name" type="xs:string" />
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="url" type="xs:string" />
                            <xs:element name="thumbnail" type="xs:string" />
                            <xs:element name="image" type="xs:string" />
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string" />
                        <xs:attribute name="count" type="xs:int" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="place" type="xs:string" />
        </xs:complexType>
    </xs:element>




</xs:schema>

=== diogocapela/isep-lprog/PL04/ex04.xml
<?xml version="1.0" encoding="UTF-8"?>



<toptracks place="United Kingdom" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ex04.xsd">
    <track name="Viva La Vida" count="1713">
        <artist name="Coldplay">
            <mbid>cc197bad-dc9c-440d-a5b5-d52ba2e14234</mbid>
            <url>http://www.last.fm/music/Coldplay</url>
        </artist>
        <url>http://www.last.fm/music/Coldplay/_/Viva+La+Vida</url>
        <thumbnail>http://userserve-ak.last.fm/serve/34/8890067.jpg</thumbnail>
        <image>http://userserve-ak.last.fm/serve/126/8890067.jpg</image>
    </track>
    <track name="Time to Pretend" count="1667">
        <artist name="MGMT">
            <mbid>c485632c-b784-4ee9-8ea1-c5fb365681fc</mbid>
            <url>http://www.last.fm/music/MGMT</url>
        </artist>
        <url>http://www.last.fm/music/MGMT/_/Time+to+Pretend</url>
        <thumbnail>http://userserve-ak.last.fm/serve/34/5916259.png</thumbnail>
        <image>http://userserve-ak.last.fm/serve/126/5916259.png</image>
    </track>
</toptracks>
